'' winSplit / FormMain_literals.vb
'' 2024 (c) manojunichiro, garagekids.

Partial Public Class FormMain

    Private Sub init_literals()

        '' japan
        literals.set_lang(literals.lang.japanese)
        literals.set_errmsg(Errno.None, "終了しました。")
        literals.set_errmsg(Errno.FinIsNotFound, "入力ファイルが見つかりません。")
        literals.set_errmsg(Errno.NewlineIsNotFound, "入力ファイルに改行コードが見つかりません。")
        literals.set_errmsg(Errno.IllegalLineLen, "入力ファイルの行の長さが異常です。")
        literals.set_errmsg(Errno.FinIsEmpty, "入力ファイルが空です。")
        literals.set_errmsg(Errno.FoutWillOverwrite, "同名の出力ファイルが既に存在するため処理を中止しました。")
        literals.set_errmsg(Errno.Exception, "想定されていないエラーが発生しました。以下のファイルを参照してください。")
        literals.set_uitext(lblFin, "入力ファイル：")
        literals.set_uitext(lblDout, "出力フォルダー：")
        literals.set_uitext2(btnDout, "FileName", "(フォルダーを選択してください)")
        literals.set_uitext2(btnDout, "Filter", "出力フォルダー|.")
        literals.set_uitext(lblMode, "分割モード：")
        literals.set_uitext(rbModeLines, "行数(&L)")
        literals.set_uitext(rbModeBytes, "バイト数(&B)")
        literals.set_uitext(rbModeFiles, "ファイル数(&F)")
        literals.set_uitext2(tbModeValue, 1, "1以上の整数を入力してください。")
        literals.set_uitext2(lblModeUnit, rbModeLines, "行")
        literals.set_uitext2(lblModeUnit, rbModeBytes, "バイト")
        literals.set_uitext2(lblModeUnit, rbModeFiles, "本")
        literals.set_uitext(btnSplit, "実行")
        literals.set_uitext2(btnSplit, "lines", "処理行数：")
        literals.set_uitext2(btnSplit, "bytes", "処理バイト数：")
        literals.set_uitext2(btnSplit, "ts", "処理時間：")
        literals.set_uitext2(btnSplit, "ts_days", "日")
        literals.set_uitext2(btnSplit, "ts_hours", "時間")
        literals.set_uitext2(btnSplit, "ts_minutes", "分")
        literals.set_uitext2(btnSplit, "ts_seconds", "秒")
        literals.set_uitext2(btnSplit, "speed", "処理速度：")
        literals.set_uitext(btnAbout, "情報")
        literals.set_uitext(btnExit, "終了")

        '' en
        literals.set_lang(literals.lang.english)
        literals.set_errmsg(Errno.None, "Process completed.")
        literals.set_errmsg(Errno.FinIsNotFound, "Input file not found.")
        literals.set_errmsg(Errno.NewlineIsNotFound, "No newline found in the input file.")
        literals.set_errmsg(Errno.IllegalLineLen, "Abnormal line length in the input file.")
        literals.set_errmsg(Errno.FinIsEmpty, "Input file is empty.")
        literals.set_errmsg(Errno.FoutWillOverwrite, "Processing is aborted because an output file with the same name already exists.")
        literals.set_errmsg(Errno.Exception, "An unexpected error occurred. Please refer to the following file.")
        literals.set_uitext(lblFin, "Input file:")
        literals.set_uitext(lblDout, "Output folder:")
        literals.set_uitext2(btnDout, "FileName", "(Select a folder)")
        literals.set_uitext2(btnDout, "Filter", "Output folder|.")
        literals.set_uitext(lblMode, "Split mode:")
        literals.set_uitext(rbModeLines, "Lines(&L)")
        literals.set_uitext(rbModeBytes, "Bytes(&B)")
        literals.set_uitext(rbModeFiles, "Files(&F)")
        literals.set_uitext2(tbModeValue, 1, "Please enter an integer greater than or equal to 1.")
        literals.set_uitext2(lblModeUnit, rbModeLines, "lines")
        literals.set_uitext2(lblModeUnit, rbModeBytes, "bytes")
        literals.set_uitext2(lblModeUnit, rbModeFiles, "files")
        literals.set_uitext(btnSplit, "Split")
        literals.set_uitext2(btnSplit, "lines", "Processed Lines")
        literals.set_uitext2(btnSplit, "bytes", "Processed Bytes")
        literals.set_uitext2(btnSplit, "ts", "Processing Time:")
        literals.set_uitext2(btnSplit, "ts_days", "days")
        literals.set_uitext2(btnSplit, "ts_hours", "hours")
        literals.set_uitext2(btnSplit, "ts_minutes", "minutes")
        literals.set_uitext2(btnSplit, "ts_seconds", "seconds")
        literals.set_uitext2(btnSplit, "speed", "Processing Speed:")
        literals.set_uitext(btnAbout, "About")
        literals.set_uitext(btnExit, "Exit")

        '' taiwan
        literals.set_lang(literals.lang.taiwanese)
        literals.set_errmsg(Errno.None, "處理完成。")
        literals.set_errmsg(Errno.FinIsNotFound, "找不到輸入文件。")
        literals.set_errmsg(Errno.NewlineIsNotFound, "在輸入文件中找不到換行符號。")
        literals.set_errmsg(Errno.IllegalLineLen, "輸入文件中的行長度異常。")
        literals.set_errmsg(Errno.FinIsEmpty, "輸入文件為空。")
        literals.set_errmsg(Errno.FoutWillOverwrite, "因為同名的輸出文件已經存在，處理被中止。")
        literals.set_errmsg(Errno.Exception, "發生了意外錯誤。請參閱以下檔案。")
        literals.set_uitext(lblFin, "輸入文件:")
        literals.set_uitext(lblDout, "輸出資料夾:")
        literals.set_uitext2(btnDout, "FileName", "(請選擇資料夾)")
        literals.set_uitext2(btnDout, "Filter", "輸出資料夾|.")
        literals.set_uitext(lblMode, "分割模式:")
        literals.set_uitext(rbModeLines, "行數(&L)")
        literals.set_uitext(rbModeBytes, "位元組數(&B)")
        literals.set_uitext(rbModeFiles, "檔案數(&F)")
        literals.set_uitext2(tbModeValue, 1, "請輸入大於或等於1的整數。")
        literals.set_uitext2(lblModeUnit, rbModeLines, "行")
        literals.set_uitext2(lblModeUnit, rbModeBytes, "位元組")
        literals.set_uitext2(lblModeUnit, rbModeFiles, "個檔案")
        literals.set_uitext(btnSplit, "執行")
        literals.set_uitext2(btnSplit, "lines", "處理行數")
        literals.set_uitext2(btnSplit, "bytes", "處理位元組")
        literals.set_uitext2(btnSplit, "ts", "處理時間:")
        literals.set_uitext2(btnSplit, "ts_days", "日")
        literals.set_uitext2(btnSplit, "ts_hours", "小時")
        literals.set_uitext2(btnSplit, "ts_minutes", "分鐘")
        literals.set_uitext2(btnSplit, "ts_seconds", "秒")
        literals.set_uitext2(btnSplit, "speed", "處理速度:")
        literals.set_uitext(btnAbout, "關於")
        literals.set_uitext(btnExit, "退出")

        '' china
        literals.set_lang(literals.lang.chinese)
        literals.set_errmsg(Errno.None, "处理完成。")
        literals.set_errmsg(Errno.FinIsNotFound, "找不到输入文件。")
        literals.set_errmsg(Errno.NewlineIsNotFound, "输入文件中找不到换行符号。")
        literals.set_errmsg(Errno.IllegalLineLen, "输入文件中的行长度异常。")
        literals.set_errmsg(Errno.FinIsEmpty, "输入文件为空。")
        literals.set_errmsg(Errno.FoutWillOverwrite, "因为同名的输出文件已经存在，处理被中止。")
        literals.set_errmsg(Errno.Exception, "发生了意外错误。请参阅以下文件。")
        literals.set_uitext(lblFin, "输入文件:")
        literals.set_uitext(lblDout, "输出文件夹:")
        literals.set_uitext2(btnDout, "FileName", "(请选择文件夹)")
        literals.set_uitext2(btnDout, "Filter", "输出文件夹|.")
        literals.set_uitext(lblMode, "分割模式:")
        literals.set_uitext(rbModeLines, "行数(&L)")
        literals.set_uitext(rbModeBytes, "字节数(&B)")
        literals.set_uitext(rbModeFiles, "文件数(&F)")
        literals.set_uitext2(tbModeValue, 1, "请输入大于或等于1的整数。")
        literals.set_uitext2(lblModeUnit, rbModeLines, "行")
        literals.set_uitext2(lblModeUnit, rbModeBytes, "字节")
        literals.set_uitext2(lblModeUnit, rbModeFiles, "个文件")
        literals.set_uitext(btnSplit, "执行")
        literals.set_uitext2(btnSplit, "lines", "处理行数")
        literals.set_uitext2(btnSplit, "bytes", "处理字节")
        literals.set_uitext2(btnSplit, "ts", "处理时间:")
        literals.set_uitext2(btnSplit, "ts_days", "天")
        literals.set_uitext2(btnSplit, "ts_hours", "小时")
        literals.set_uitext2(btnSplit, "ts_minutes", "分钟")
        literals.set_uitext2(btnSplit, "ts_seconds", "秒")
        literals.set_uitext2(btnSplit, "speed", "处理速度:")
        literals.set_uitext(btnAbout, "关于")
        literals.set_uitext(btnExit, "退出")

        '' korea
        literals.set_lang(literals.lang.korean)
        literals.set_errmsg(Errno.None, "처리가 완료되었습니다.")
        literals.set_errmsg(Errno.FinIsNotFound, "입력 파일을 찾을 수 없습니다.")
        literals.set_errmsg(Errno.NewlineIsNotFound, "입력 파일에 줄 바꿈 코드가 없습니다.")
        literals.set_errmsg(Errno.IllegalLineLen, "입력 파일의 줄 길이가 비정상적입니다.")
        literals.set_errmsg(Errno.FinIsEmpty, "입력 파일이 비어 있습니다.")
        literals.set_errmsg(Errno.FoutWillOverwrite, "동일한 이름의 출력 파일이 이미 존재하기 때문에 처리가 중단되었습니다.")
        literals.set_errmsg(Errno.Exception, "예기치 않은 오류가 발생했습니다. 다음 파일을 참조하세요.")
        literals.set_uitext(lblFin, "입력 파일:")
        literals.set_uitext(lblDout, "출력 폴더:")
        literals.set_uitext2(btnDout, "FileName", "(폴더를 선택하세요)")
        literals.set_uitext2(btnDout, "Filter", "출력 폴더|.")
        literals.set_uitext(lblMode, "분할 모드:")
        literals.set_uitext(rbModeLines, "라인(&L)")
        literals.set_uitext(rbModeBytes, "바이트(&B)")
        literals.set_uitext(rbModeFiles, "파일(&F)")
        literals.set_uitext2(tbModeValue, 1, "1 이상의 정수를 입력하세요.")
        literals.set_uitext2(lblModeUnit, rbModeLines, "라인")
        literals.set_uitext2(lblModeUnit, rbModeBytes, "바이트")
        literals.set_uitext2(lblModeUnit, rbModeFiles, "개 파일")
        literals.set_uitext(btnSplit, "실행")
        literals.set_uitext2(btnSplit, "lines", "처리 라인")
        literals.set_uitext2(btnSplit, "bytes", "처리 바이트")
        literals.set_uitext2(btnSplit, "ts", "처리 시간:")
        literals.set_uitext2(btnSplit, "ts_days", "일")
        literals.set_uitext2(btnSplit, "ts_hours", "시간")
        literals.set_uitext2(btnSplit, "ts_minutes", "분")
        literals.set_uitext2(btnSplit, "ts_seconds", "초")
        literals.set_uitext2(btnSplit, "speed", "처리 속도:")
        literals.set_uitext(btnAbout, "소개")
        literals.set_uitext(btnExit, "종료")

    End Sub

End Class

'' EOF
